---
defaultGroups:
    - wheel
    - audio
    - video
    - input
    - network
    - storage
    - lp
    - power
autologinGroup: autologin
doAutologin: false
sudoersGroup: wheel
setRootPassword: false
doReusePassword: false
availableShells: /bin/bash, /usr/bin/zsh
avatarFilePath: ""
passwordRequirements:
    minLength: 1
    maxLength: -1
